name: moover
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro:
  google_maps_flutter:
  country_code_picker:
  firebase_auth:
  location:
  flutter_google_places:
  shared_preferences: 0.4.3
  geolocator:
  http:
  cloud_firestore:
  geocoder:
  page_transition:
  dio:
  intl:
  flutter_share:
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/locationFlag.png
    - assets/locationPerson.png
    - assets/switchOff.png
    - assets/switchOn.png
    - assets/profileImage.jpg
    - assets/rating.png
    - assets/carShadeDrawer.png
    - assets/logo.png
    - assets/car-white.png
    - assets/envelope.png
    - assets/lock.png
    - assets/car.png
    - assets/München.png
    - assets/home.png
    - assets/clock.png
    - assets/arrow1.png
    - assets/calender1.png
    - assets/cash1.png
    - assets/info1.png
    - assets/profile1.png
    - assets/tick1.png
    - assets/mail.png
    - assets/call.png

  fonts:
   - family: Gibson
     fonts:
       - asset: assets/fonts/Gibson-Regular.ttf
       - asset: assets/fonts/Gibson-RegularItalic.ttf
         style: italic
       - asset: assets/fonts/gibson-bold.ttf